version: '2'

services:
  puppet:
    hostname: puppet.local
    build: ./puppet-image
    image: puppet:latest
    volumes:
      - ./production:/etc/puppetlabs/code/environments/production
    networks:
      - lan
    ports:
      - 8140
  server1:
    hostname: server1.local
    build: ./server-image
    image: server:latest
    networks:
      - lan

networks:
  lan:
