version: '2'

services:
  puppet:
    container_name: puppet
    hostname: puppet
    image: puppet
    networks:
      - lan
    ports:
      - 8140
    volumes:
      - ./production:/etc/puppetlabs/code/environments/production
  server1:
    container_name: server1
    hostname: server1
    image: server
    networks:
      - lan

networks:
  lan:
